ALTER TABLE organization.eqms_product_default_applicable_specification DROP CONSTRAINT fk_epdas_product_subtype_lk_id;
ALTER TABLE organization.eqms_product_default_applicable_specification DROP CONSTRAINT fk_epbas_product_type_lk_id;
ALTER TABLE organization.eqms_product_default_applicable_specification DROP CONSTRAINT fk_epbas_product_group_lk_id;
ALTER TABLE organization.eqms_product_default_applicable_specification DROP CONSTRAINT fk_epbas_organization_id;
ALTER TABLE organization.eqms_product_default_applicable_specification DROP CONSTRAINT fk_epbas_design_specification_type_lk_id;
ALTER TABLE organization.eqms_product_default_applicable_specification DROP CONSTRAINT epdas_tenant_org_ref_unique;
