CREATE TABLE workflow.eqms_project_tasks_history (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fk_eqms_project_tasks_id integer,
    eqms_tenant_key integer,
    fk_eqms_organization_id integer,
    fk_eqms_project_instance_header_id integer,
    task_name character varying(255),
    task_stage_order integer,
    task_order integer,
    status smallint,
    record_status smallint DEFAULT '1'::smallint,
    version numeric(10,1),
    valid_from_date timestamp without time zone,
    valid_to_date timestamp without time zone DEFAULT '2199-12-31 23:59:59'::timestamp without time zone,
    created_date timestamp without time zone,
    created_by integer,
    modified_date timestamp without time zone,
    modified_by integer,
    has_subtask smallint,
    task_data jsonb,
    fk_eqms_workflow_task_status_id integer,
    task_description character varying(3500),
    fk_eqms_default_workflow_task_status_id integer,
    fk_eqms_project_type_tasks_id integer 
);

