CREATE TABLE workflow.eqms_project_workflow_journal (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    eqms_tenant_key integer,
    fk_eqms_organization_id integer,
    fk_eqms_user_id integer,
    fk_eqms_project_instance_id integer,
    fk_eqms_old_project_workflow_status_id integer,
    fk_eqms_new_project_workflow_status_id integer,
    fk_eqms_project_tasks_id integer,
    fk_eqms_project_member_role_id integer,
    fk_eqms_role_lk_ref_id integer,
    project_name character varying(100),
    project_version numeric(10,1),
    old_workflow_status_name character varying(100),
    new_workflow_status_name character varying(100),
    task_name character varying(100),
    assigned_role_name character varying(100),
    status smallint,
    created_date timestamp without time zone,
    created_by integer,
    modified_date timestamp without time zone,
    modified_by integer,
    task_description character varying(3500),
    assigned_date timestamp without time zone 
);

