ALTER TABLE organization.eqms_functional_block_type_lk DROP CONSTRAINT fk_efbtl_organization_id;
ALTER TABLE organization.eqms_functional_block_type_lk DROP CONSTRAINT eqms_functional_block_type_lk_tenant_org_ref_unique;
