ALTER TABLE organization.eqms_design_transfer_checklist_template_mapper_lk DROP CONSTRAINT fk_edtctml_organization_id;
ALTER TABLE organization.eqms_design_transfer_checklist_template_mapper_lk DROP CONSTRAINT fk_edtctml_document_template_id;
ALTER TABLE organization.eqms_design_transfer_checklist_template_mapper_lk DROP CONSTRAINT fk_edtctml_design_transfer_checklist_lk_id;
