CREATE TABLE hrcs.eqms_organization_employee (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    eqms_tenant_key integer,
    fk_eqms_organization_id integer,
    encrypted_employee_id character varying,
    encrypted_employee_first_name character varying,
    encrypted_employee_last_name character varying,
    status smallint,
    created_date timestamp without time zone,
    created_by integer,
    modified_date timestamp without time zone,
    modified_by integer,
    fk_eqms_hr_resource_requisition_id integer,
    fk_eqms_role_lk_id integer,
    fk_eqms_organization_department_id integer,
    fk_eqms_hr_employment_type_lk_id integer,
    fk_eqms_signature_image_id integer,
    encrypted_age character varying,
    joining_date timestamp without time zone,
    actual_educational_qualification character varying(50),
    actual_experience integer,
    actual_area_of_expertise character varying(500),
    training_and_certifications_details character varying(500),
    fk_eqms_hr_candidate_evalution_id integer,
    fk_eqms_employee_status_lk_id integer,
    hash_employee_number_token character varying(500),
    fk_eqms_designation_lk_id integer 
);

