CREATE TABLE regulation.eqms_reg_conformity_declaration_history (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fk_eqms_reg_conformity_declaration_id integer,
    eqms_tenant_key integer,
    fk_eqms_organization_id integer,
    fk_eqms_project_id integer,
    manufacture_contact_details character varying,
    manufacture_trade_name character varying,
    product_brand_name character varying,
    product_code character varying,
    product_catalogue_number character varying,
    regulation_conformity smallint,
    conformilty_assessment_route character varying,
    general_applicable_directives character varying,
    notified_body_number character varying,
    applicable_common_specification character varying,
    applied_standards character varying,
    competent_authority character varying,
    authorized_representative character varying,
    place character varying,
    conformity_declaration_date timestamp without time zone,
    status smallint,
    record_status smallint DEFAULT 1,
    version numeric(10,1),
    valid_from_date timestamp without time zone,
    valid_to_date timestamp without time zone DEFAULT '2199-12-31 23:59:59'::timestamp without time zone,
    created_date timestamp without time zone,
    created_by integer,
    modified_date timestamp without time zone,
    modified_by integer,
    fk_eqms_reg_product_classification_id integer,
    notified_body_name character varying 
);

