DO $$ 
DECLARE 
VAR_TENANT_KEY INT := ${TENANTKEY}; 
VAR_ORG_ID INT := ${ORGID}; 

BEGIN
-- eqms_form_action_wf_status_mapping
INSERT INTO abac.eqms_form_action_wf_status_mapping(
  eqms_tenant_key, fk_eqms_organization_id, fk_eqms_form_controls_id,
  fk_eqms_workflow_task_status_id, status, created_date, created_by, modified_date, modified_by
)
VALUES
-- Test license
(VAR_TENANT_KEY,VAR_ORG_ID,256,28,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,257,29,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,258,32,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,259,NULL,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,258,30,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,257,31,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,255,NULL,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,260,28,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,260,27,1,NOW(),1,NULL,NULL),
-- Manufacturing license
(VAR_TENANT_KEY,VAR_ORG_ID,262,28,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,263,29,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,264,32,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,265,NULL,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,264,30,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,263,31,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,261,NULL,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,266,28,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,266,27,1,NOW(),1,NULL,NULL),
-- Device Master
(VAR_TENANT_KEY,VAR_ORG_ID,268,28,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,269,29,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,270,32,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,271,NULL,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,270,30,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,269,31,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,267,NULL,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,272,28,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,272,27,1,NOW(),1,NULL,NULL),
-- Plan Master
(VAR_TENANT_KEY,VAR_ORG_ID,274,28,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,275,29,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,276,32,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,277,NULL,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,276,30,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,275,31,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,273,NULL,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,278,28,1,NOW(),1,NULL,NULL),
(VAR_TENANT_KEY,VAR_ORG_ID,278,27,1,NOW(),1,NULL,NULL);
END $$;