CREATE TABLE dnd.eqms_dig_specification (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fk_eqms_organization_id integer,
    specification_description text,
    specification_parameter character varying(100),
    specification_value character varying(100),
    specification_unit character varying(100),
    tolerance_percentage character varying(20),
    status smallint,
    created_date timestamp without time zone,
    created_by integer,
    modified_date timestamp without time zone,
    modified_by integer,
    eqms_tenant_key integer,
    fk_eqms_project_applicable_specification_id integer,
    adverse_event character varying(100),
    fk_eqms_usability_type_id integer,
    hazard_number character varying(100),
    hazardous_event character varying(100),
    risk_control_measure character varying(100),
    lifetime_of_device character varying(100),
    fk_eqms_device_lk_id integer,
    applicable_standards character varying(100),
    clause_no_of_applicable character varying(100),
    fk_eqms_project_design_input_gathering_id integer,
    intended_users character varying(3500),
    intended_population character varying(3500),
    indications_of_use character varying(3500),
    rule_law_act character varying(3500),
    mode_of_connectivity character varying(255),
    connectivity character varying(3500),
    communication_protocol character varying(3500),
    fk_eqms_labelling_packaging_type_lk_id integer,
    label_symbol character varying,
    fk_eqms_use_environment_lk_id integer,
    fk_eqms_rcm_type_lk_id integer,
    fk_eqms_alarm_type_id integer 
);

