ALTER TABLE organization.eqms_pre_prod_incoming_inspection_spec_criteria_lk DROP CONSTRAINT fk_eiiscl_organization_id;
ALTER TABLE organization.eqms_pre_prod_incoming_inspection_spec_criteria_lk DROP CONSTRAINT fk_eiiscl_incoming_inspection_spec_group_lk_is;
ALTER TABLE organization.eqms_pre_prod_incoming_inspection_spec_criteria_lk DROP CONSTRAINT unique_eiisc_tnt_org_ref_id;
