ALTER TABLE organization.eqms_market_demography_sub_category_lk DROP CONSTRAINT fk_emdscl_organization_id;
ALTER TABLE organization.eqms_market_demography_sub_category_lk DROP CONSTRAINT fk_emdscl_market_demography_category_lk_id;
ALTER TABLE organization.eqms_market_demography_sub_category_lk DROP CONSTRAINT eqms_market_demography_sub_category_lk_tenant_org_ref_unique;
