CREATE TABLE vendor.eqms_sample_order_inspection_history (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fk_eqms_sample_order_inspection_id integer,
    eqms_tenant_key integer,
    fk_eqms_organization_id integer,
    fk_eqms_sample_orders_id integer,
    supply_reference_number character varying(100),
    supply_received integer,
    quality_received integer,
    inspection_quantity integer,
    remarks character varying(2500),
    qc_result smallint,
    status smallint,
    record_status smallint DEFAULT 1,
    version numeric(10,1),
    valid_from_date timestamp without time zone,
    valid_to_date timestamp without time zone DEFAULT '2199-12-31 23:59:59'::timestamp without time zone,
    created_date timestamp without time zone,
    created_by integer,
    modified_date timestamp without time zone,
    modified_by integer NOT NULL,
    fk_eqms_part_lk_id integer,
    fk_eqms_verification_result_lk_id integer,
    fk_eqms_sample_inspection_procedure_files_id integer 
);

