DO $$ 
DECLARE 
VAR_TENANT_KEY INT := ${TENANTKEY}; 
VAR_ORG_ID INT := ${ORGID}; 

BEGIN
--Risk Module
INSERT INTO organization.eqms_module (eqms_tenant_key, fk_eqms_organization_id, ref_id, module_name, module_type, module_slug, status, created_date, created_by)
VALUES (VAR_TENANT_KEY, VAR_ORG_ID, 5,'Risk', 1, 'risk', 1, NOW(), 1); 

INSERT INTO abac.eqms_form (
  eqms_tenant_key, fk_eqms_organization_id, form_name, status, created_date, created_by, fk_eqms_form_type_lk_id, is_parallel_allowed, completion_tracking, fk_eqms_entity_subscription_id, ref_id, slug
) VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 'Scope', 1, NOW(), 1, 3, 'FALSE', 'FALSE', NULL, 79, 'scope'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Applicability', 1, NOW(), 1, 3, 'FALSE', 'FALSE', NULL, 80, 'applicability'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Other hazards', 1, NOW(), 1, 3, 'FALSE', 'FALSE', NULL, 81, 'other_hazards'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Risk Review Requirement', 1, NOW(), 1, 3, 'FALSE', 'FALSE', NULL, 82, 'risk_review_requirement'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Risk Team', 1, NOW(), 1, 3, 'FALSE', 'FALSE', NULL, 83, 'risk_team'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Committee', 1, NOW(), 1, 3, 'FALSE', 'FALSE', NULL, 84, 'committee'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Risk Level Definition', 1, NOW(), 1, 3, 'FALSE', 'FALSE', NULL, 85, 'risk_level_definition'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Risk Assessment Matrix', 1, NOW(), 1, 3, 'FALSE', 'FALSE', NULL, 86, 'risk_assessment_matrix'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Residual Risk Level', 1, NOW(), 1, 3, 'FALSE', 'FALSE', NULL, 87, 'residual_risk_level'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Pre Post Production Info', 1, NOW(), 1, 1, 'FALSE', 'FALSE', NULL, 88, 'pre_post_production_info'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Risk Analysis And Control', 1, NOW(), 1, 1, 'FALSE', 'FALSE', NULL, 89, 'risk_analysis_and_control'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Hazard Identification Used', 1, NOW(), 1, 1, 'FALSE', 'FALSE', NULL, 90, 'hazard_identification_used'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Benefit Risk Analysis', 1, NOW(), 1, 1, 'FALSE', 'FALSE', NULL, 91, 'benefit_risk_analysis'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Risk Management Plan', 1, NOW(), 1, 1, 'FALSE', 'FALSE', NULL, 92, 'risk_management_plan'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Risk Management Plan Record Generation', 1, NOW(), 1, 1, 'FALSE', 'FALSE', NULL, 133, 'risk_management_plan_record_generation'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Risk Management File Record Generation', 1, NOW(), 1, 1, 'FALSE', 'FALSE', NULL, 134, 'risk_management_file_record_generation'),

(VAR_TENANT_KEY, VAR_ORG_ID, 'individual_risk_analysis', 1, NOW(), 1, 3, 'FALSE', 'FALSE', NULL, 147, 'individual_risk_analysis'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'hazard_identification_tool', 1, NOW(), 1, 3, 'FALSE', 'FALSE', NULL, 148, 'hazard_identification_tool'),

(VAR_TENANT_KEY, VAR_ORG_ID, 'risk_review_report_summary', 1, NOW(), 1, 3, 'FALSE', 'FALSE', NULL, 152, 'risk_review_report_summary'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'risk_review', 1, NOW(), 1, 1, 'FALSE', 'FALSE', NULL, 153, 'risk_review'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'record_generation_risk_chart_before_mitigation', 1, NOW(), 1, 1, 'FALSE', 'FALSE', NULL, 154, 'record_generation_risk_chart_before_mitigation'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'record_generation_risk_chart_after_mitigation', 1, NOW(), 1, 1, 'FALSE', 'FALSE', NULL, 155, 'record_generation_risk_chart_after_mitigation'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'record_generation_hazards', 1, NOW(), 1, 1, 'FALSE', 'FALSE', NULL, 156, 'record_generation_hazards'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'record_generation_benefit_risk_analysis', 1, NOW(), 1, 1, 'FALSE', 'FALSE', NULL, 157, 'record_generation_benefit_risk_analysis');
-- eqms_form_controls
INSERT INTO abac.eqms_form_menu_mapping (
  eqms_tenant_key, fk_eqms_organization_id, fk_eqms_form_id, fk_eqms_menu_lk_id, status, created_date, created_by
) VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 79, 76, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 80, 79, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 81, 81, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 82, 85, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 83, 77, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 84, 78, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 85, 80, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 86, 83, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 87, 84, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 88, 86, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 89, 82, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 91, 88, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 92, 20, 1, NOW(), 1),
--record generation form mappings
(VAR_TENANT_KEY, VAR_ORG_ID, 88, 219, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 133, 219, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 134, 220, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 88, 222, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 88, 221, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 88, 224, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 147, 292, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 90, 288, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 148, 287, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 153, 294, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 152, 293, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 154, 222, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 155, 222, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 156, 223, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 157, 224, 1, NOW(), 1);



INSERT INTO abac.eqms_form_controls (
  eqms_tenant_key, fk_eqms_organization_id, fk_eqms_form_id, action_name, status, created_date, created_by, modified_date, modified_by, action_type, ref_id
) VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 79, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 292),
(VAR_TENANT_KEY, VAR_ORG_ID, 79, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 293),
(VAR_TENANT_KEY, VAR_ORG_ID, 79, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 294),
(VAR_TENANT_KEY, VAR_ORG_ID, 79, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 295),
(VAR_TENANT_KEY, VAR_ORG_ID, 79, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 296),
(VAR_TENANT_KEY, VAR_ORG_ID, 79, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 297),
(VAR_TENANT_KEY, VAR_ORG_ID, 80, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 298),
(VAR_TENANT_KEY, VAR_ORG_ID, 80, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 299),
(VAR_TENANT_KEY, VAR_ORG_ID, 80, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 300),
(VAR_TENANT_KEY, VAR_ORG_ID, 80, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 301),
(VAR_TENANT_KEY, VAR_ORG_ID, 80, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 302),
(VAR_TENANT_KEY, VAR_ORG_ID, 80, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 303),
(VAR_TENANT_KEY, VAR_ORG_ID, 81, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 304),
(VAR_TENANT_KEY, VAR_ORG_ID, 81, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 305),
(VAR_TENANT_KEY, VAR_ORG_ID, 81, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 306),
(VAR_TENANT_KEY, VAR_ORG_ID, 81, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 307),
(VAR_TENANT_KEY, VAR_ORG_ID, 81, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 308),
(VAR_TENANT_KEY, VAR_ORG_ID, 81, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 309),
(VAR_TENANT_KEY, VAR_ORG_ID, 82, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 310),
(VAR_TENANT_KEY, VAR_ORG_ID, 82, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 311),
(VAR_TENANT_KEY, VAR_ORG_ID, 82, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 312),
(VAR_TENANT_KEY, VAR_ORG_ID, 82, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 313),
(VAR_TENANT_KEY, VAR_ORG_ID, 82, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 314),
(VAR_TENANT_KEY, VAR_ORG_ID, 82, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 315),
(VAR_TENANT_KEY, VAR_ORG_ID, 83, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 316),
(VAR_TENANT_KEY, VAR_ORG_ID, 83, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 317),
(VAR_TENANT_KEY, VAR_ORG_ID, 83, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 318),
(VAR_TENANT_KEY, VAR_ORG_ID, 83, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 319),
(VAR_TENANT_KEY, VAR_ORG_ID, 83, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 320),
(VAR_TENANT_KEY, VAR_ORG_ID, 83, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 321),
(VAR_TENANT_KEY, VAR_ORG_ID, 84, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 322),
(VAR_TENANT_KEY, VAR_ORG_ID, 84, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 323),
(VAR_TENANT_KEY, VAR_ORG_ID, 84, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 324),
(VAR_TENANT_KEY, VAR_ORG_ID, 84, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 325),
(VAR_TENANT_KEY, VAR_ORG_ID, 84, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 326),
(VAR_TENANT_KEY, VAR_ORG_ID, 84, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 327),
(VAR_TENANT_KEY, VAR_ORG_ID, 85, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 328),
(VAR_TENANT_KEY, VAR_ORG_ID, 85, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 329),
(VAR_TENANT_KEY, VAR_ORG_ID, 85, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 330),
(VAR_TENANT_KEY, VAR_ORG_ID, 85, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 331),
(VAR_TENANT_KEY, VAR_ORG_ID, 85, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 332),
(VAR_TENANT_KEY, VAR_ORG_ID, 85, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 333),
(VAR_TENANT_KEY, VAR_ORG_ID, 86, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 334),
(VAR_TENANT_KEY, VAR_ORG_ID, 86, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 335),
(VAR_TENANT_KEY, VAR_ORG_ID, 86, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 336),
(VAR_TENANT_KEY, VAR_ORG_ID, 86, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 337),
(VAR_TENANT_KEY, VAR_ORG_ID, 86, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 338),
(VAR_TENANT_KEY, VAR_ORG_ID, 86, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 339),
(VAR_TENANT_KEY, VAR_ORG_ID, 87, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 340),
(VAR_TENANT_KEY, VAR_ORG_ID, 87, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 341),
(VAR_TENANT_KEY, VAR_ORG_ID, 87, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 342),
(VAR_TENANT_KEY, VAR_ORG_ID, 87, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 343),
(VAR_TENANT_KEY, VAR_ORG_ID, 87, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 344),
(VAR_TENANT_KEY, VAR_ORG_ID, 87, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 345),
(VAR_TENANT_KEY, VAR_ORG_ID, 88, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 346),
(VAR_TENANT_KEY, VAR_ORG_ID, 88, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 347),
(VAR_TENANT_KEY, VAR_ORG_ID, 88, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 348),
(VAR_TENANT_KEY, VAR_ORG_ID, 88, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 349),
(VAR_TENANT_KEY, VAR_ORG_ID, 88, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 350),
(VAR_TENANT_KEY, VAR_ORG_ID, 88, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 351),
(VAR_TENANT_KEY, VAR_ORG_ID, 89, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 352),
(VAR_TENANT_KEY, VAR_ORG_ID, 89, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 353),
(VAR_TENANT_KEY, VAR_ORG_ID, 89, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 354),
(VAR_TENANT_KEY, VAR_ORG_ID, 89, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 355),
(VAR_TENANT_KEY, VAR_ORG_ID, 89, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 356),
(VAR_TENANT_KEY, VAR_ORG_ID, 89, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 357),
(VAR_TENANT_KEY, VAR_ORG_ID, 90, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 358),
(VAR_TENANT_KEY, VAR_ORG_ID, 90, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 359),
(VAR_TENANT_KEY, VAR_ORG_ID, 90, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 360),
(VAR_TENANT_KEY, VAR_ORG_ID, 90, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 361),
(VAR_TENANT_KEY, VAR_ORG_ID, 90, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 362),
(VAR_TENANT_KEY, VAR_ORG_ID, 90, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 363),
(VAR_TENANT_KEY, VAR_ORG_ID, 91, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 364),
(VAR_TENANT_KEY, VAR_ORG_ID, 91, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 365),
(VAR_TENANT_KEY, VAR_ORG_ID, 91, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 366),
(VAR_TENANT_KEY, VAR_ORG_ID, 91, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 367),
(VAR_TENANT_KEY, VAR_ORG_ID, 91, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 368),
(VAR_TENANT_KEY, VAR_ORG_ID, 91, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 369),
(VAR_TENANT_KEY, VAR_ORG_ID, 153, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 422),
(VAR_TENANT_KEY, VAR_ORG_ID, 153, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 423),
(VAR_TENANT_KEY, VAR_ORG_ID, 153, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 424),
(VAR_TENANT_KEY, VAR_ORG_ID, 153, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 425),
(VAR_TENANT_KEY, VAR_ORG_ID, 153, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 426),
(VAR_TENANT_KEY, VAR_ORG_ID, 153, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 427);

-- added on 22-11-2025

INSERT INTO abac.eqms_form_control_actions (
  eqms_tenant_key, fk_eqms_organization_id, fk_eqms_form_controls_id, requires_role_validation, is_transition_action, status, created_date, created_by
) VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 292, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 293, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 294, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 295, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 296, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 297, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 298, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 299, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 300, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 301, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 302, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 303, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 304, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 305, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 306, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 307, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 308, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 309, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 310, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 311, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 312, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 313, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 314, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 315, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 316, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 317, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 318, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 319, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 320, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 321, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 322, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 323, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 324, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 325, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 326, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 327, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 328, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 329, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 330, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 331, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 332, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 333, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 334, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 335, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 336, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 337, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 338, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 339, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 340, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 341, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 342, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 343, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 344, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 345, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 346, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 347, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 348, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 349, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 350, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 351, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 352, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 353, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 354, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 355, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 356, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 357, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 358, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 359, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 360, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 361, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 362, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 363, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 364, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 365, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 366, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 367, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 368, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 369, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 422, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 423, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 424, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 425, 'FALSE', 'TRUE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 426, 'FALSE', 'FALSE', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 427, 'FALSE', 'TRUE', 1, NOW(), 1);


END $$;


