DO $$ 
DECLARE 
VAR_TENANT_KEY INT := ${TENANTKEY}; 
VAR_ORG_ID INT := ${ORGID}; 

BEGIN
-- eqms_module
INSERT INTO organization.eqms_module (eqms_tenant_key, fk_eqms_organization_id, ref_id, module_name, module_type, module_slug, status, created_date, created_by)
VALUES (VAR_TENANT_KEY, VAR_ORG_ID, 1,'Design & Development', 1, 'design-development', 1, NOW(), 1); 
 
-- eqms_entity_subscription
INSERT INTO organization.eqms_entity_subscription (eqms_tenant_key, fk_eqms_organization_id, ref_id, fk_eqms_subscribed_module_id, subscription_status, status, created_date, created_by)
VALUES (VAR_TENANT_KEY, VAR_ORG_ID, 1, 1, 1, 1, NOW(), 1);

--eqms_form
INSERT INTO abac.eqms_form (eqms_tenant_key, fk_eqms_organization_id, form_name, status, created_date, created_by, modified_date, modified_by, fk_eqms_form_type_lk_id, is_parallel_allowed, completion_tracking, fk_eqms_entity_subscription_id, ref_id, slug)
VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 'Project', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 1, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Market research and study', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 2, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'HLD', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 3, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Feasibility Study', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 4, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Product Realization Plan', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 5, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'PND', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 6, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'PND Review', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 7, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'UAT Validation Plan', 1, NOW(), 1, NULL, NULL, 1, true, false, NULL, 8, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Design Project Plan', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 9, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Functional Block', 1, NOW(), 1, NULL, NULL, 1, true, false, NULL, 10, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Applicable specification', 1, NOW(), 1, NULL, NULL, 1, true, false, NULL, 11, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Pilot validation Report', 1, NOW(), 1, NULL, NULL, 1, true, false, NULL, 15, NULL), -- changes 2 to null for entity
(VAR_TENANT_KEY, VAR_ORG_ID, 'Specification', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 16, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Intended Use', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 17, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'DIR', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 18, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Design input adequacy checklist', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 19, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'design Quality plan', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 20, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'concept', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 21, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'prototype', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 22, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'prototype verification plan', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 23, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'prototype verification report', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 24, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Design Quality Report', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 25, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'pre transfer design output document', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 26, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'initiate test license', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 27, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'clinical evaluation', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 28, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Add Installation Procedure', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 29, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Design Output Document', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 30, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'QMS Clause Applicability', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 31, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'I/O Traceability Matrix', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 32, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Acknowledgement of design Transfer', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 33, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Initiate Manufacturing License', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 34, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'pilot Validation Plan', 1, NOW(), 1, NULL, NULL, 1, true, false, NULL, 35, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Pilot', 1, NOW(), 1, NULL, NULL, 1, true, false, NULL, 44, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'pilot verification plan', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 45, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'pilot verification report', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 46, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'pilot design Review report', 1, NOW(), 1, NULL, NULL, 1, true, false, NULL, 47, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Product Life Declaration', 1, NOW(), 1, NULL, NULL, 1, false, false, NULL, 49, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'prototype design Review report', 1, NOW(), 1, NULL, NULL, 1, true, false, NULL, 50, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Design History File', 1, NOW(), 1, NULL, NULL, 1, true, false, NULL, 75, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Feasibility Study Record Generation', 1, NOW(), 1, NULL, NULL, 3, false, false, NULL,97, 'feasibility_study_record_generation'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Product Realisation Plan Record Generation Form', 1, NOW(), 1, NULL, NULL, 3, false, false, NULL, 102, 'product_realisation_plan_record_generation_form'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Product Need Document Record Generation Form', 1, NOW(), 1, NULL, NULL, 3, false, false, NULL, 103, 'product_need_document_record_generation_form'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'PND Project Review Report Record Generation Form', 1, NOW(), 1, NULL, NULL, 3, false, false, NULL, 104, 'pnd_project_review_report_record_generation_form'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Design Project Plan Record Generation Form', 1, NOW(), 1, NULL, NULL, 3, false, false, NULL, 105, 'design_project_plan_record_generation_form'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Intended Use Record Generation Form', 1, NOW(), 1, NULL, NULL, 3, false, false, NULL, 106, 'intended_use_record_generation_form'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Design Input Adequacy Check List Record Generation Form', 1, NOW(), 1, NULL, NULL, 3, false, false, NULL, 107, 'design_input_adequacy_check_list_record_generation_form'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Design Quality Plan Record Generation Form', 1, NOW(), 1, NULL, NULL, 3, false, false, NULL, 108, 'design_quality_plan_record_generation_form'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Design Verification Plan Record Generation Form', 1, NOW(), 1, NULL, NULL, 3, false, false, NULL, 109, 'design_verification_plan_record_generation_form'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Design Validation Plan Record Generation Form', 1, NOW(), 1, NULL, NULL, 3, false, false, NULL, 110, 'design_validation_plan_record_generation_form'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Design Validation Report Record Generation Form', 1, NOW(), 1, NULL, NULL, 3, false, false, NULL, 111, 'design_validation_report_record_generation_form'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Product Life Declaration Record Generation Form', 1, NOW(), 1, NULL, NULL, 3, false, false, NULL, 112, 'product_life_declaration_record_generation_form'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Design Output File Record Generation Form', 1, NOW(), 1, NULL, NULL, 3, false, false, NULL, 113, 'design_output_file_record_generation_form'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Design Inputs to Output Traceability Matrix Record Generation Form', 1, NOW(), 1, NULL, NULL, 3, false, false, NULL, 114, 'design_inputs_to_output_traceability_matrix_record_generation_form'),
(VAR_TENANT_KEY, VAR_ORG_ID, 'Acknowledge Design Transfer Check List Record Generation Form', 1, NOW(), 1, NULL, NULL, 3, false, false, NULL, 115, 'design_transfer_check_list_record_generation_form');

--eqms_form_controls
INSERT INTO abac.eqms_form_controls (eqms_tenant_key, fk_eqms_organization_id, fk_eqms_form_id, action_name, status, created_date, created_by, modified_date, modified_by, action_type, ref_id)
VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 2),
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 3),
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 4),
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 5),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 6),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, 'Add New', 1, NOW(), 1, NULL, NULL, NULL, 7),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, 'Initiate Design Feasibility Study', 1, NOW(), 1, NULL, NULL, NULL, 8),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 9),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 10),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 11),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 12),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 13),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 14),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 15),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 16),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 'Send it for CEO Review', 1, NOW(), 1, NULL, NULL, NULL, 17),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 18),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 19),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 20),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 21),
(VAR_TENANT_KEY, VAR_ORG_ID, 5, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 22),
(VAR_TENANT_KEY, VAR_ORG_ID, 5, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 23),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 24),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 25),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 26),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 27),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 28),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 29),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, 'Initiate PND Review', 1, NOW(), 1, NULL, NULL, NULL, 30),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 31),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 32),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 33),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 34),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 35),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 36),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 'Initiate Approval', 1, NOW(), 1, NULL, NULL, NULL, 37),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 'Request Modification', 1, NOW(), 1, NULL, NULL, NULL, 38),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 'Generate PND Report', 1, NOW(), 1, NULL, NULL, NULL, 39),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 'Start Design', 1, NOW(), 1, NULL, NULL, NULL, 40),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 'CEO Decision', 1, NOW(), 1, NULL, NULL, NULL, 41),
(VAR_TENANT_KEY, VAR_ORG_ID, 5, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 42),
(VAR_TENANT_KEY, VAR_ORG_ID, 5, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 43),
(VAR_TENANT_KEY, VAR_ORG_ID, 5, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 44),
(VAR_TENANT_KEY, VAR_ORG_ID, 5, 'Submit for Approval', 1, NOW(), 1, NULL, NULL, NULL, 45),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 46),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 47),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 48),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 49),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 50),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, 'Submit for Approval', 1, NOW(), 1, NULL, NULL, NULL, 51),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, 'Initiate Design Input Gathering', 1, NOW(), 1, NULL, NULL, NULL, 52),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 53),
(VAR_TENANT_KEY, VAR_ORG_ID, 10, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 54),
(VAR_TENANT_KEY, VAR_ORG_ID, 10, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 55),
(VAR_TENANT_KEY, VAR_ORG_ID, 10, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 56),
(VAR_TENANT_KEY, VAR_ORG_ID, 10, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 57),
(VAR_TENANT_KEY, VAR_ORG_ID, 10, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 58),
(VAR_TENANT_KEY, VAR_ORG_ID, 11, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 59),
(VAR_TENANT_KEY, VAR_ORG_ID, 11, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 60),
(VAR_TENANT_KEY, VAR_ORG_ID, 11, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 61),
(VAR_TENANT_KEY, VAR_ORG_ID, 11, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 62),
(VAR_TENANT_KEY, VAR_ORG_ID, 11, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 63),
(VAR_TENANT_KEY, VAR_ORG_ID, 15, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 79),
(VAR_TENANT_KEY, VAR_ORG_ID, 15, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 80),
(VAR_TENANT_KEY, VAR_ORG_ID, 15, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 81),
(VAR_TENANT_KEY, VAR_ORG_ID, 15, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 82),
(VAR_TENANT_KEY, VAR_ORG_ID, 15, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 83),
(VAR_TENANT_KEY, VAR_ORG_ID, 16, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 84),
(VAR_TENANT_KEY, VAR_ORG_ID, 16, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 85),
(VAR_TENANT_KEY, VAR_ORG_ID, 16, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 86),
(VAR_TENANT_KEY, VAR_ORG_ID, 16, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 87),
(VAR_TENANT_KEY, VAR_ORG_ID, 16, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 88),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 89),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 90),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 91),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 92),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 93),
(VAR_TENANT_KEY, VAR_ORG_ID, 18, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 94),
(VAR_TENANT_KEY, VAR_ORG_ID, 18, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 95),
(VAR_TENANT_KEY, VAR_ORG_ID, 18, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 96),
(VAR_TENANT_KEY, VAR_ORG_ID, 18, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 97),
(VAR_TENANT_KEY, VAR_ORG_ID, 18, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 98),
(VAR_TENANT_KEY, VAR_ORG_ID, 18, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 99),
(VAR_TENANT_KEY, VAR_ORG_ID, 19, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 100),
(VAR_TENANT_KEY, VAR_ORG_ID, 19, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 101),
(VAR_TENANT_KEY, VAR_ORG_ID, 19, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 102),
(VAR_TENANT_KEY, VAR_ORG_ID, 19, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 103),
(VAR_TENANT_KEY, VAR_ORG_ID, 19, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 104),
(VAR_TENANT_KEY, VAR_ORG_ID, 20, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 105),
(VAR_TENANT_KEY, VAR_ORG_ID, 20, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 106),
(VAR_TENANT_KEY, VAR_ORG_ID, 20, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 107),
(VAR_TENANT_KEY, VAR_ORG_ID, 20, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 108),
(VAR_TENANT_KEY, VAR_ORG_ID, 20, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 109),
(VAR_TENANT_KEY, VAR_ORG_ID, 21, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 110),
(VAR_TENANT_KEY, VAR_ORG_ID, 21, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 111),
(VAR_TENANT_KEY, VAR_ORG_ID, 21, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 112),
(VAR_TENANT_KEY, VAR_ORG_ID, 21, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 113),
(VAR_TENANT_KEY, VAR_ORG_ID, 21, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 114),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 115),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 116),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 117),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 118),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 119),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 120),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 121),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 122),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 123),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 124),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 125),
(VAR_TENANT_KEY, VAR_ORG_ID, 26, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 126),
(VAR_TENANT_KEY, VAR_ORG_ID, 26, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 127),
(VAR_TENANT_KEY, VAR_ORG_ID, 26, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 128),
(VAR_TENANT_KEY, VAR_ORG_ID, 26, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 129),
(VAR_TENANT_KEY, VAR_ORG_ID, 26, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 130),
(VAR_TENANT_KEY, VAR_ORG_ID, 27, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 131),
(VAR_TENANT_KEY, VAR_ORG_ID, 27, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 132),
(VAR_TENANT_KEY, VAR_ORG_ID, 27, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 133),
(VAR_TENANT_KEY, VAR_ORG_ID, 27, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 134),
(VAR_TENANT_KEY, VAR_ORG_ID, 27, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 135),
(VAR_TENANT_KEY, VAR_ORG_ID, 28, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 136),
(VAR_TENANT_KEY, VAR_ORG_ID, 28, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 137),
(VAR_TENANT_KEY, VAR_ORG_ID, 28, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 138),
(VAR_TENANT_KEY, VAR_ORG_ID, 28, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 139),
(VAR_TENANT_KEY, VAR_ORG_ID, 28, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 140),
(VAR_TENANT_KEY, VAR_ORG_ID, 29, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 141),
(VAR_TENANT_KEY, VAR_ORG_ID, 29, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 142),
(VAR_TENANT_KEY, VAR_ORG_ID, 29, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 143),
(VAR_TENANT_KEY, VAR_ORG_ID, 29, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 144),
(VAR_TENANT_KEY, VAR_ORG_ID, 29, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 145),
(VAR_TENANT_KEY, VAR_ORG_ID, 30, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 146),
(VAR_TENANT_KEY, VAR_ORG_ID, 30, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 147),
(VAR_TENANT_KEY, VAR_ORG_ID, 30, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 148),
(VAR_TENANT_KEY, VAR_ORG_ID, 30, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 149),
(VAR_TENANT_KEY, VAR_ORG_ID, 30, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 150),
(VAR_TENANT_KEY, VAR_ORG_ID, 31, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 151),
(VAR_TENANT_KEY, VAR_ORG_ID, 31, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 152),
(VAR_TENANT_KEY, VAR_ORG_ID, 31, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 153),
(VAR_TENANT_KEY, VAR_ORG_ID, 31, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 154),
(VAR_TENANT_KEY, VAR_ORG_ID, 31, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 155),
(VAR_TENANT_KEY, VAR_ORG_ID, 32, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 156),
(VAR_TENANT_KEY, VAR_ORG_ID, 32, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 157),
(VAR_TENANT_KEY, VAR_ORG_ID, 32, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 158),
(VAR_TENANT_KEY, VAR_ORG_ID, 32, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 159),
(VAR_TENANT_KEY, VAR_ORG_ID, 32, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 160),
(VAR_TENANT_KEY, VAR_ORG_ID, 33, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 161),
(VAR_TENANT_KEY, VAR_ORG_ID, 33, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 162),
(VAR_TENANT_KEY, VAR_ORG_ID, 33, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 163),
(VAR_TENANT_KEY, VAR_ORG_ID, 33, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 164),
(VAR_TENANT_KEY, VAR_ORG_ID, 33, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 165),
(VAR_TENANT_KEY, VAR_ORG_ID, 34, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 166),
(VAR_TENANT_KEY, VAR_ORG_ID, 34, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 167),
(VAR_TENANT_KEY, VAR_ORG_ID, 34, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 168),
(VAR_TENANT_KEY, VAR_ORG_ID, 34, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 169),
(VAR_TENANT_KEY, VAR_ORG_ID, 34, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 170),
(VAR_TENANT_KEY, VAR_ORG_ID, 35, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 171),
(VAR_TENANT_KEY, VAR_ORG_ID, 35, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 172),
(VAR_TENANT_KEY, VAR_ORG_ID, 35, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 173),
(VAR_TENANT_KEY, VAR_ORG_ID, 35, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 174),
(VAR_TENANT_KEY, VAR_ORG_ID, 35, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 175),
(VAR_TENANT_KEY, VAR_ORG_ID, 35, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 176),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 177),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 178),
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 179),
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 180),
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 181),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 182),
(VAR_TENANT_KEY, VAR_ORG_ID, 11, 'Check', 1, NOW(), 1, NULL, NULL, NULL, 183),
(VAR_TENANT_KEY, VAR_ORG_ID, 8, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 184),
(VAR_TENANT_KEY, VAR_ORG_ID, 8, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 185),
(VAR_TENANT_KEY, VAR_ORG_ID, 8, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 186),
(VAR_TENANT_KEY, VAR_ORG_ID, 8, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 187),
(VAR_TENANT_KEY, VAR_ORG_ID, 8, 'Submit for Approval', 1, NOW(), 1, NULL, NULL, NULL, 188),
(VAR_TENANT_KEY, VAR_ORG_ID, 8, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 189),
(VAR_TENANT_KEY, VAR_ORG_ID, 25, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 208),
(VAR_TENANT_KEY, VAR_ORG_ID, 25, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 209),
(VAR_TENANT_KEY, VAR_ORG_ID, 25, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 210),
(VAR_TENANT_KEY, VAR_ORG_ID, 25, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 211),
(VAR_TENANT_KEY, VAR_ORG_ID, 25, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 212),
(VAR_TENANT_KEY, VAR_ORG_ID, 25, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 213),
(VAR_TENANT_KEY, VAR_ORG_ID, 45, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 214),
(VAR_TENANT_KEY, VAR_ORG_ID, 45, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 215),
(VAR_TENANT_KEY, VAR_ORG_ID, 45, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 216),
(VAR_TENANT_KEY, VAR_ORG_ID, 45, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 217),
(VAR_TENANT_KEY, VAR_ORG_ID, 45, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 218),
(VAR_TENANT_KEY, VAR_ORG_ID, 45, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 219),
(VAR_TENANT_KEY, VAR_ORG_ID, 46, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 220),
(VAR_TENANT_KEY, VAR_ORG_ID, 46, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 221),
(VAR_TENANT_KEY, VAR_ORG_ID, 46, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 222),
(VAR_TENANT_KEY, VAR_ORG_ID, 46, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 223),
(VAR_TENANT_KEY, VAR_ORG_ID, 46, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 224),
(VAR_TENANT_KEY, VAR_ORG_ID, 46, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 225),
(VAR_TENANT_KEY, VAR_ORG_ID, 24, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 226),
(VAR_TENANT_KEY, VAR_ORG_ID, 24, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 227),
(VAR_TENANT_KEY, VAR_ORG_ID, 24, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 228),
(VAR_TENANT_KEY, VAR_ORG_ID, 24, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 229),
(VAR_TENANT_KEY, VAR_ORG_ID, 24, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 230),
(VAR_TENANT_KEY, VAR_ORG_ID, 24, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 231),
(VAR_TENANT_KEY, VAR_ORG_ID, 34, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 232),
(VAR_TENANT_KEY, VAR_ORG_ID, 34, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 233),
(VAR_TENANT_KEY, VAR_ORG_ID, 34, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 234),
(VAR_TENANT_KEY, VAR_ORG_ID, 34, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 235),
(VAR_TENANT_KEY, VAR_ORG_ID, 34, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 236),
(VAR_TENANT_KEY, VAR_ORG_ID, 47, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 237),
(VAR_TENANT_KEY, VAR_ORG_ID, 47, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 238),
(VAR_TENANT_KEY, VAR_ORG_ID, 47, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 239),
(VAR_TENANT_KEY, VAR_ORG_ID, 47, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 240),
(VAR_TENANT_KEY, VAR_ORG_ID, 47, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 241),
(VAR_TENANT_KEY, VAR_ORG_ID, 47, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 242),
(VAR_TENANT_KEY, VAR_ORG_ID, 50, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 243),
(VAR_TENANT_KEY, VAR_ORG_ID, 50, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 244),
(VAR_TENANT_KEY, VAR_ORG_ID, 50, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 245),
(VAR_TENANT_KEY, VAR_ORG_ID, 50, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 246),
(VAR_TENANT_KEY, VAR_ORG_ID, 50, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 247),
(VAR_TENANT_KEY, VAR_ORG_ID, 50, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 248),
(VAR_TENANT_KEY, VAR_ORG_ID, 44, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 279),
(VAR_TENANT_KEY, VAR_ORG_ID, 44, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 280),
(VAR_TENANT_KEY, VAR_ORG_ID, 44, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 281),
(VAR_TENANT_KEY, VAR_ORG_ID, 44, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 282),
(VAR_TENANT_KEY, VAR_ORG_ID, 44, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 283),
(VAR_TENANT_KEY, VAR_ORG_ID, 44, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 284),
(VAR_TENANT_KEY, VAR_ORG_ID, 50, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 285),
(VAR_TENANT_KEY, VAR_ORG_ID, 49, 'Submit For Approval', 1, NOW(), 1, NULL, NULL, NULL, 286),
(VAR_TENANT_KEY, VAR_ORG_ID, 49, 'Submit For Review', 1, NOW(), 1, NULL, NULL, NULL, 287),
(VAR_TENANT_KEY, VAR_ORG_ID, 49, 'Approve', 1, NOW(), 1, NULL, NULL, NULL, 288),
(VAR_TENANT_KEY, VAR_ORG_ID, 49, 'Reject', 1, NOW(), 1, NULL, NULL, NULL, 289),
(VAR_TENANT_KEY, VAR_ORG_ID, 49, 'Cancel', 1, NOW(), 1, NULL, NULL, NULL, 290),
(VAR_TENANT_KEY, VAR_ORG_ID, 49, 'Save', 1, NOW(), 1, NULL, NULL, NULL, 291),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, 'Add New', 1, NOW(), 1, NULL, NULL, NULL, 370),
(VAR_TENANT_KEY, VAR_ORG_ID, 45, 'Add New', 1, NOW(), 1, NULL, NULL, NULL, 371);


--eqms_form_control_actions
-- DND Form Control Actions Insert Statements based on form-control-action-dnd.csv
INSERT INTO abac.eqms_form_control_actions (eqms_tenant_key, fk_eqms_organization_id, fk_eqms_form_controls_id, requires_role_validation, is_transition_action, status, created_date, created_by, modified_date, modified_by)
VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 1, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 8, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 10, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 11, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 12, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 13, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 15, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 16, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 18, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 19, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 20, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 24, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 25, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 26, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 27, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 28, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 30, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 31, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 32, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 33, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 34, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 35, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 37, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 38, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 39, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 40, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 5, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 14, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 21, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 29, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 36, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 41, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 42, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 43, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 44, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 45, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 49, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 46, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 47, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 48, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 50, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 51, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 52, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 53, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 54, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 55, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 56, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 57, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 58, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 59, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 60, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 61, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 62, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 63, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 79, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 80, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 81, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 82, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 83, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 84, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 85, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 86, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 87, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 88, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 89, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 90, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 91, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 94, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 95, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 96, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 97, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 98, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 99, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 100, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 101, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 102, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 103, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 104, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 105, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 106, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 107, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 108, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 109, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 110, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 111, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 112, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 113, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 114, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 115, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 116, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 117, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 118, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 119, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 120, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 121, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 122, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 123, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 124, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 125, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 126, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 127, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 128, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 129, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 130, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 131, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 132, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 133, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 134, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 135, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 136, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 137, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 138, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 139, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 140, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 141, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 142, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 143, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 183, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 185, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 186, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 187, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 188, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 189, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 184, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 208, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 209, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 210, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 211, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 212, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 213, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 214, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 215, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 216, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 217, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 218, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 219, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 220, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 221, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 222, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 223, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 224, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 225, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 226, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 227, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 228, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 229, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 230, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 231, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 232, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 233, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 234, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 235, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 236, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 237, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 238, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 239, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 240, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 241, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 242, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 243, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 244, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 245, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 246, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 247, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 248, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 92, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 93, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 279, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 280, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 281, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 282, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 283, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 284, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 285, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 286, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 287, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 288, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 289, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 290, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 291, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 151, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 152, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 155, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 154, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 153, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 171, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 172, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 173, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 175, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 176, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 174, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 146, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 147, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 148, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 149, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 150, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 156, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 157, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 158, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 160, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 159, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 161, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 162, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 163, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 164, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 165, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 166, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 167, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 168, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 169, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 170, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 145, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 144, false, false, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 370, false, true, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 371, false, true, 1, NOW(), 1, NULL, NULL);

--eqms_form_menu_mapping
INSERT INTO abac.eqms_form_menu_mapping (eqms_tenant_key, fk_eqms_organization_id, fk_eqms_form_id, fk_eqms_menu_lk_id, status, created_date, created_by, modified_date, modified_by)
VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 8, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, 49, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, 180, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, 50, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 97, 181, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 51, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 179, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 179, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 5, 52, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, 53, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 54, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 8, 173, 0, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, 57, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 10, 59, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 11, 58, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 15, 174, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 15, 174, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 16, 141, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 16, 60, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, 61, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, 61, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 18, 141, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 19, 63, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 20, 64, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 20, 64, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 21, 165, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, 166, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, 167, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 24, 168, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 25, 65, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 26, 66, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 27, 67, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 28, 68, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 29, 69, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 30, 70, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 31, 71, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 32, 72, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 33, 73, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 34, 74, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 35, 173, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 44, 169, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 45, 170, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 45, 170, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 46, 171, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 46, 171, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 46, 148, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 47, 176, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 47, 145, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 47, 176, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 49, 185, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 50, 175, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 75, 140, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 102, 182, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 103, 183, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 104, 184, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 105, 143, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 106, 161, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 108, 144, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 109, 147, 1, NOW(), 1, NULL, NULL), 
(VAR_TENANT_KEY, VAR_ORG_ID, 110, 149, 1, NOW(), 1, NULL, NULL), 
(VAR_TENANT_KEY, VAR_ORG_ID, 111, 150, 1, NOW(), 1, NULL, NULL), 
(VAR_TENANT_KEY, VAR_ORG_ID, 112, 153, 1, NOW(), 1, NULL, NULL), 
(VAR_TENANT_KEY, VAR_ORG_ID, 113, 146, 1, NOW(), 1, NULL, NULL), 
(VAR_TENANT_KEY, VAR_ORG_ID, 114, 157, 1, NOW(), 1, NULL, NULL), 
(VAR_TENANT_KEY, VAR_ORG_ID, 115, 151, 1, NOW(), 1, NULL, NULL);

INSERT INTO abac.eqms_object (
  eqms_tenant_key,
  fk_eqms_organization_id,
  object_type,
  object_name,
  status,
  created_date,
  created_by,
  modified_date,
  modified_by,
  is_context_driven,
  object_description,
  entity_id,
  fk_eqms_owner_id,
  ref_id
) VALUES
  (VAR_TENANT_KEY, VAR_ORG_ID, 'form', 'Applicable Specification', 1, now(), 1, NULL, NULL, 0, NULL, 11, NULL, 1),
  (VAR_TENANT_KEY, VAR_ORG_ID, 'form', 'DIR', 1, now(), 1, NULL, NULL, 0, NULL, 18, NULL, 2);


-- EQMS Policy Insert Statements based on eqms_policy.csv
INSERT INTO abac.eqms_policy (eqms_tenant_key, fk_eqms_organization_id, name, description, access_type, logical_gate, status, created_date, created_by, modified_date, modified_by, ref_id)
VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 'regulatory Head Checkbox Policy', 'Allows regulatory  head to uncheck checkbox', 'Allow', 'AND', 1, NOW(), 1, NULL, NULL, 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 'DIR-OWNER', 'Allow only owner to edit DIR', 'Deny', 'AND', 1, NOW(), 1, NULL, NULL, 2);


-- EQMS Policy Actions Insert Statements based on eqms_policy_actions.csv
INSERT INTO abac.eqms_policy_actions (eqms_tenant_key, fk_eqms_organization_id, fk_eqms_policy_id, fk_eqms_action_lk_id, status, created_date, created_by, modified_date, modified_by)
VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 1, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, 2, 1, NOW(), 1, NULL, NULL),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, 3, 1, NOW(), 1, NULL, NULL);


INSERT INTO abac.eqms_object_attributes (
  eqms_tenant_key,
  fk_eqms_organization_id,
  fk_eqms_object_id,
  key,
  value,
  status,
  created_date,
  created_by,
  modified_date,
  modified_by
) VALUES
  (VAR_TENANT_KEY, VAR_ORG_ID, 1, 'regulatory_head_role_id', '17', 1, now(), 1, NULL, NULL);
  -- 4. eqms_policy_attributes
INSERT INTO abac.eqms_policy_attributes (
  eqms_tenant_key,
  fk_eqms_organization_id,
  fk_eqms_policy_id,
  subject_key,
  object_key,
  attribute_type,
  operator,
  status,
  created_date,
  created_by,
  modified_date,
  modified_by
) VALUES
  (VAR_TENANT_KEY, VAR_ORG_ID, 2, 'user_id', 'owner_id', NULL, 'not_equals', 1, now(), 1, NULL, NULL),
  (VAR_TENANT_KEY, VAR_ORG_ID, 1, 'role_id', 'regulatory_head_role_id', NULL, 'equals', 1, now(), 1, NULL, NULL);
 
INSERT INTO abac.eqms_object_policy_mapper (
  eqms_tenant_key,
  fk_eqms_organization_id,
  fk_eqms_object_id,
  fk_eqms_policy_id,
  priority,
  status,
  created_date,
  created_by,
  modified_date,
  modified_by
) VALUES
  (VAR_TENANT_KEY, VAR_ORG_ID, 1, 1, 0, 1, now(), 1, NULL, NULL),
  (VAR_TENANT_KEY, VAR_ORG_ID, 2, 2, 0, 1, now(), 1, NULL, NULL);

END $$;