DO $$ 
DECLARE 
VAR_TENANT_KEY INT := ${TENANTKEY}; 
VAR_ORG_ID INT := ${ORGID}; 

BEGIN

INSERT INTO organization.eqms_entity_template (
  eqms_tenant_key, fk_eqms_organization_id, ref_id, fk_eqms_nomenclature_category_id, entity_title, entity_version, slug, is_annexure, fk_parent_entity_id, fk_eqms_module_id, status, created_date, created_by
) VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 2, 'performance-specifications', 1, 'performance-specifications', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, 2, 'shelf-life', 1, 'shelf-life', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, 2, 'statutory', 1, 'statutory', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 2, 'safety', 1, 'safety', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 5, 2, 'regulations', 1, 'regulations', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, 2, 'other-requirements', 1, 'other-requirements', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 2, 'other-device-compatibility', 1, 'other-device-compatibility', 'false', NULL, NULL, 1, NOW(), 1),  
(VAR_TENANT_KEY, VAR_ORG_ID, 8, 2, 'accessories-&-consumables', 1, 'accessories-&-consumables', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, 2, 'toxicity-&-biocompatability', 1, 'toxicity-&-biocompatability', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 10, 2, 'reliability-requirements', 1, 'reliability-requirements', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 11, 2, 'sterilization-requirements', 1, 'sterilization-requirements', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 12, 2, 'lifetime-of-the-device', 1, 'lifetime-of-the-device', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 13, 2, 'training-requirements-for-customers', 1, 'training-requirements-for-customers', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 14, 2, 'references-from-the-previous-design', 1, 'references-from-the-previous-design', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 15, 2, 'adverse-events-design-input', 1, 'adverse-events-design-input', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 16, 2, 'risk-control-measures', 1, 'risk-control-measures', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, 2, 'servicing-requirements', 1, 'servicing-requirements', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 18, 2, 'installation-requirements', 1, 'installation-requirements', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 19, 2, 'manufacturing-process', 1, 'manufacturing-process', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 20, 2, 'storage-&-handling-requirements', 1, 'storage-&-handling-requirements', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 21, 2, 'labelling-and-packaging-requirements', 1, 'labelling-and-packaging-requirements', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, 2, 'software-requirements', 1, 'software-requirements', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, 2, 'environmental-specifications', 1, 'environmental-specifications', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 24, 2, 'communication-protocol', 1, 'communication-protocol', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 25, 2, 'usability-interface-specifications', 1, 'usability-interface-specifications', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 26, 2, 'power-supply', 1, 'power-supply', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 27, 2, 'physical-characteristics', 1, 'physical-characteristics', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 28, 2, 'user-and-patient-requirements', 1, 'user-and-patient-requirements', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 29, 2, 'functional-specifications', 1, 'functional-specifications', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 73, 2, 'intended-use', 1, 'intended-use', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 79, 2, 'alarms', 1, 'alarms', 'false', NULL, NULL, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 80, 2, 'standards', 1, 'standards', 'false', NULL, NULL, 1, NOW(), 1);
INSERT INTO organization.eqms_nomenclature_sequence_defs (
  eqms_tenant_key, fk_eqms_organization_id, ref_id, sequence_name, increment_by, min_value, max_value, status, created_date, created_by
) VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 'PERFORMANCE-SPECIFICATIONS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, 'SHELF-LIFE_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, 'STATUTORY_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 'SAFETY_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 5, 'REGULATIONS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, 'OTHER-REQUIREMENTS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 'OTHER-DEVICE-COMPATIBILITY_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 8, 'ACCESSORIES-&-CONSUMABLES_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, 'TOXICITY-&-BIOCOMPATABILITY_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 10, 'RELIABILITY-REQUIREMENTS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 11, 'STERILIZATION-REQUIREMENTS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 12, 'LIFETIME-OF-THE-DEVICE_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 13, 'TRAINING-REQUIREMENTS-FOR-CUSTOMERS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 14, 'REFERENCES-FROM-THE-PREVIOUS-DESIGN_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 15, 'ADVERSE-EVENTS-DESIGN-INPUT_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 16, 'RISK-CONTROL-MEASURES_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, 'SERVICING-REQUIREMENTS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 18, 'INSTALLATION-REQUIREMENTS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 19, 'MANUFACTURING-PROCESS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 20, 'STORAGE-&-HANDLING-REQUIREMENTS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 21, 'LABELLING-AND-PACKAGING-REQUIREMENTS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, 'SOFTWARE-REQUIREMENTS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, 'ENVIRONMENTAL-SPECIFICATIONS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),        
(VAR_TENANT_KEY, VAR_ORG_ID, 24, 'COMMUNICATION-PROTOCOL_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 25, 'USABILITY-INTERFACE-SPECIFICATIONS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),  
(VAR_TENANT_KEY, VAR_ORG_ID, 26, 'POWER-SUPPLY_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 27, 'PHYSICAL-CHARACTERISTICS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 28, 'USER-AND-PATIENT-REQUIREMENTS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),       
(VAR_TENANT_KEY, VAR_ORG_ID, 29, 'FUNCTIONAL-SPECIFICATIONS_SPECIFICATION SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 30, 'INTENDED-USE_SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 31, 'ALARMS_SEQUENCE', 1, 1, 10000, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 32, 'STANDARDS_SEQUENCE', 1, 1, 10000, 1, NOW(), 1);

INSERT INTO organization.eqms_nomenclature_name_parts (
  eqms_tenant_key, fk_eqms_organization_id, ref_id, fk_eqms_entity_template_id, part_value, part_order, fk_eqms_sequence_def_id, fk_eqms_nomenclature_part_type_id, status, created_date, created_by
) VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 1, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, 1, 'performance-specifications', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, 1, NULL, 3, 1, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 2, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 5, 2, 'shelf-life', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, 2, NULL, 3, 2, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 3, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 8, 3, 'statutory', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, 3, NULL, 3, 3, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 10, 4, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 11, 4, 'safety', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 12, 4, NULL, 3, 4, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 13, 5, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 14, 5, 'regulations', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 15, 5, NULL, 3, 5, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 16, 6, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, 6, 'other-requirements', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 18, 6, NULL, 3, 6, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 19, 7, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 20, 7, 'other-device-compatibility', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 21, 7, NULL, 3, 7, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, 8, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, 8, 'accessories-&-consumables', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 24, 8, NULL, 3, 8, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 25, 9, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 26, 9, 'toxicity-&-biocompatability', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 27, 9, NULL, 3, 9, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 28, 10, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 29, 10, 'reliability-requirements', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 30, 10, NULL, 3, 10, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 31, 11, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 32, 11, 'sterilization-requirements', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 33, 11, NULL, 3, 11, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 34, 12, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 35, 12, 'lifetime-of-the-device', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 36, 12, NULL, 3, 12, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 37, 13, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 38, 13, 'training-requirements-for-customers', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 39, 13, NULL, 3, 13, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 40, 14, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 41, 14, 'references-from-the-previous-design', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 42, 14, NULL, 3, 14, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 43, 15, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 44, 15, 'adverse-events-design-input', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 45, 15, NULL, 3, 15, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 46, 16, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 47, 16, 'risk-control-measures', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 48, 16, NULL, 3, 16, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 49, 17, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 50, 17, 'servicing-requirements', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 51, 17, NULL, 3, 17, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 52, 18, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 53, 18, 'installation-requirements', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 54, 18, NULL, 3, 18, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 55, 19, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 56, 19, 'manufacturing-process', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 57, 19, NULL, 3, 19, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 58, 20, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 59, 20, 'storage-&-handling-requirements', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 60, 20, NULL, 3, 20, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 61, 21, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 62, 21, 'labelling-and-packaging-requirements', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 63, 21, NULL, 3, 21, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 64, 22, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 65, 22, 'software-requirements', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 66, 22, NULL, 3, 22, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 67, 23, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 68, 23, 'environmental-specifications', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 69, 23, NULL, 3, 23, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 70, 24, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 71, 24, 'communication-protocol', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 72, 24, NULL, 3, 24, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 73, 25, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 74, 25, 'usability-interface-specifications', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 75, 25, NULL, 3, 25, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 76, 26, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 77, 26, 'power-supply', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 78, 26, NULL, 3, 26, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 79, 27, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 80, 27, 'physical-characteristics', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 81, 27, NULL, 3, 27, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 82, 28, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 83, 28, 'user-and-patient-requirements', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 84, 28, NULL, 3, 28, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 85, 29, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 86, 29, 'functional-specifications', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 87, 29, NULL, 3, 29, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 260, 73, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 261, 73, 'intended-use', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 262, 73, NULL, 3, 30, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 283, 79, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 284, 79, 'alarms', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 285, 79, NULL, 3, 31, 4, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 286, 80, NULL, 1, NULL, 3, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 287, 80, 'standards', 2, NULL, 2, 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 288, 80, NULL, 3, 32, 4, 1, NOW(), 1);


INSERT INTO organization.eqms_nomenclature_delimiter (
  eqms_tenant_key, fk_eqms_entity_template_id, fk_eqms_organization_id, delimiter, status, created_date, created_by
) VALUES
(VAR_TENANT_KEY, 1, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 2, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 3, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 4, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 5, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 6, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 7, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 8, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 9, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 10, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 11, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 12, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 13, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 14, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 15, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 16, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 17, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 18, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 19, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 20, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 21, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 22, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 23, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 24, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 25, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 26, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 27, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 28, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 29, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 73, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 79, VAR_ORG_ID, '_', 1, NOW(), 1),
(VAR_TENANT_KEY, 80, VAR_ORG_ID, '_', 1, NOW(), 1);



INSERT INTO organization.eqms_nomenclature_sequence_counters (
  eqms_tenant_key, fk_eqms_organization_id, fk_eqms_sequence_def_id, scope_key_value, current_value, last_generated_at, status, created_date, created_by
) VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 5, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 8, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 10, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 11, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 12, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 13, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 14, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 15, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 16, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 18, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 19, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 20, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 21, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 24, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 25, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 26, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 27, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 28, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 29, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 30, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 31, 'DEFAULT', 0, NOW(), 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 32, 'DEFAULT', 0, NOW(), 1, NOW(), 1);


INSERT INTO organization.eqms_entity_nomenclature_mappings (
  eqms_tenant_key, fk_eqms_organization_id, ref_id, fk_eqms_nomenclature_name_part_id, related_table, related_column, status, created_date, created_by
) VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 1, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, 4, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, 7, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 10, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 5, 13, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, 16, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 19, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 8, 22, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, 25, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 10, 28, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 11, 31, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 12, 34, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 13, 37, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 14, 40, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 15, 43, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 16, 46, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, 49, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 18, 52, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 19, 55, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 20, 58, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 21, 61, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, 64, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, 67, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 24, 70, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 25, 73, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 26, 76, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 27, 79, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 28, 82, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 29, 85, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 73, 260, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 79, 283, 'dnd.eqms_project', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 80, 286, 'dnd.eqms_project', 'id', 1, NOW(), 1);


INSERT INTO organization.eqms_nomenclature_mapping_conditions (
  eqms_tenant_key, fk_eqms_organization_id, fk_eqms_entity_nomenclature_mapping_id, fk_eqms_mapping_join_id, condition_order, condition_expression, status, created_date, created_by
) VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 1, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 5, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 8, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 10, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 11, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 12, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 13, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 14, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 15, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 16, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 18, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 19, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 20, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 21, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 24, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 25, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 26, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 27, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 28, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 29, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 73, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 79, NULL, 1, '@id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 80, NULL, 1, '@id', 1, NOW(), 1);


INSERT INTO organization.eqms_nomenclature_mapping_joins (
  eqms_tenant_key, fk_eqms_organization_id, ref_id, fk_eqms_entity_nomenclature_mapping_id, join_order, fk_eqms_nomenclature_join_type_id, join_table, join_on_left, join_on_right, status, created_date, created_by
) VALUES
(VAR_TENANT_KEY, VAR_ORG_ID, 1, 1, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 2, 2, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 3, 3, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 4, 4, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 5, 5, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 6, 6, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 7, 7, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 8, 8, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 9, 9, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 10, 10, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 11, 11, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 12, 12, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 13, 13, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 14, 14, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 15, 15, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 16, 16, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 17, 17, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 18, 18, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 19, 19, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 20, 20, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 21, 21, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 22, 22, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 23, 23, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 24, 24, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 25, 25, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 26, 26, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 27, 27, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 28, 28, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 29, 29, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 73, 73, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 79, 79, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1),
(VAR_TENANT_KEY, VAR_ORG_ID, 80, 80, 1, 1, 'dnd.eqms_project', 'id', 'id', 1, NOW(), 1);

END $$;
