ALTER TABLE pre_production.eqms_pre_prod_product_trace_card_process_checklist DROP CONSTRAINT fk_eppptcpc_pre_prod_product_traceability_card_id;
ALTER TABLE pre_production.eqms_pre_prod_product_traceability_card DROP CONSTRAINT fk_epptc_pre_prod_bom_assembly_part_item_details_id;
ALTER TABLE pre_production.eqms_pre_prod_product_traceability_card DROP CONSTRAINT fk_eppptc_organization_id;
ALTER TABLE pre_production.eqms_pre_prod_product_trace_card_process_checklist DROP CONSTRAINT fk_eppptcpc_status_lk_id;
ALTER TABLE pre_production.eqms_pre_prod_product_trace_card_process_checklist DROP CONSTRAINT fk_eppptcpc_process_checklist_lk_id;
ALTER TABLE pre_production.eqms_pre_prod_product_trace_card_process_checklist DROP CONSTRAINT fk_eppptcpc_process_checklist_group_lk_id;
ALTER TABLE pre_production.eqms_pre_prod_product_trace_card_process_checklist DROP CONSTRAINT fk_eppptcpc_organization_id;
ALTER TABLE pre_production.eqms_pre_prod_product_trace_card_process_checklist DROP CONSTRAINT fk_eppfop_project_id;
