ALTER TABLE organization.eqms_product_default_design_transfer_document DROP CONSTRAINT fk_epddtd_product_type_lk_id;
ALTER TABLE organization.eqms_product_default_design_transfer_document DROP CONSTRAINT fk_epddtd_product_group_lk_id;
ALTER TABLE organization.eqms_product_default_design_transfer_document DROP CONSTRAINT fk_epddtd_organization_id;
ALTER TABLE organization.eqms_product_default_design_transfer_document DROP CONSTRAINT fk_epdas_product_subtype_lk_id;
ALTER TABLE organization.eqms_product_default_design_transfer_document DROP CONSTRAINT fk_epdas_design_transfer_checklist_lk_id;
ALTER TABLE organization.eqms_product_default_design_transfer_document DROP CONSTRAINT epddtd_tenant_org_ref_unique;
