ALTER TABLE organization.eqms_hr_induction_training_topic_supporting_file DROP CONSTRAINT fk_ehittsf_supporting_file_id;
ALTER TABLE organization.eqms_hr_induction_training_topic_supporting_file DROP CONSTRAINT fk_ehittsf_organization_id;
ALTER TABLE organization.eqms_hr_induction_training_topic_supporting_file DROP CONSTRAINT fk_ehittsf_hr_induction_training_topic_lk_id;
ALTER TABLE organization.eqms_hr_induction_training_topic_supporting_file DROP CONSTRAINT ehittsf_tenant_org_ref_unique;
