ALTER TABLE risk_management.eqms_project_risk_severity_level DROP CONSTRAINT fk_erpst_risk_severity_level_template_id;
ALTER TABLE risk_management.eqms_project_risk_severity_level DROP CONSTRAINT fk_eprsl_project_id;
ALTER TABLE risk_management.eqms_project_risk_severity_level DROP CONSTRAINT fk_eprsl_organization_id;
ALTER TABLE risk_management.eqms_project_risk_probability_level DROP CONSTRAINT fk_erppt_risk_probability_level_template_id;
ALTER TABLE risk_management.eqms_project_risk_probability_level DROP CONSTRAINT fk_eprpl_project_id;
ALTER TABLE risk_management.eqms_project_risk_probability_level DROP CONSTRAINT fk_eprpl_organization_id;
