CREATE TABLE vendor.eqms_vendors_history (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fk_eqms_vendors_id integer NOT NULL,
    eqms_tenant_key integer,
    fk_eqms_organization_id integer,
    fk_eqms_vendor_type_lk_id integer,
    fk_eqms_vendor_re_evaluation_frequency_lk_id integer,
    encrypted_vendor_name character varying,
    encrypted_address character varying,
    encrypted_location character varying,
    encrypted_contact_person_name character varying,
    encrypted_telephone_number character varying,
    encrypted_email character varying,
    encrypted_website character varying,
    record_status smallint DEFAULT 1,
    version numeric(10,1),
    valid_from_date timestamp without time zone,
    valid_to_date timestamp without time zone DEFAULT '2199-12-31 23:59:59'::timestamp without time zone,
    created_date timestamp without time zone,
    created_by integer,
    modified_date timestamp without time zone,
    modified_by integer,
    fk_eqms_status_lk_id integer 
);

