ALTER TABLE regulation.eqms_reg_manufacture_license_supporting_files DROP CONSTRAINT fk_ertmsf_fk_eqms_reg_manufacture_license_id;
ALTER TABLE regulation.eqms_reg_manufacture_license_supporting_files DROP CONSTRAINT fk_ertmsf_eqms_organization_id;
ALTER TABLE regulation.eqms_reg_manufacture_license_supporting_files DROP CONSTRAINT fk_ertmsf_eqms_file_id;
ALTER TABLE regulation.eqms_reg_manufacture_license DROP CONSTRAINT fk_erml_fk_eqms_project_id;
ALTER TABLE regulation.eqms_reg_manufacture_license DROP CONSTRAINT fk_erml_eqms_reg_manufacture_checklist_section_master_id;
ALTER TABLE regulation.eqms_reg_manufacture_license DROP CONSTRAINT fk_erml_eqms_organization_id;
