CREATE TABLE regulation.eqms_reg_dmf_executive_summary_history (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fk_eqms_reg_dmf_executive_summary_id integer,
    eqms_tenant_key integer,
    fk_eqms_organization_id integer,
    fk_eqms_reg_device_master_file_id integer,
    novel_feature character varying,
    sterilization_information character varying,
    regulatory_status character varying,
    clinical_evaluation character varying,
    risk_management_controls character varying,
    declaration_conformity character varying,
    device_domestic_price character varying,
    non_viable_cell_tissue_derivative character varying,
    microbial_recombinant_origin_material character varying,
    irradiating_component_type character varying,
    status smallint,
    record_status smallint DEFAULT 1,
    version numeric(10,1),
    valid_from_date timestamp without time zone,
    valid_to_date timestamp without time zone DEFAULT '2199-12-31 23:59:59'::timestamp without time zone,
    created_date timestamp without time zone,
    created_by integer,
    modified_date timestamp without time zone,
    modified_by integer 
);

