CREATE TABLE sales.eqms_customer_feedback_history (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fk_eqms_customer_feedback_id integer,
    eqms_tenant_key integer,
    fk_eqms_organization_id integer,
    fk_eqms_organization_product_id integer,
    fk_eqms_customer_master_id integer,
    fk_eqms_order_acknowledgement_id integer,
    product_serial_number character varying(100),
    installation_date timestamp without time zone,
    fk_eqms_feedback_source_id integer,
    feedback_date timestamp without time zone,
    fk_eqms_organization_employee_id integer,
    feedback text,
    record_status smallint DEFAULT 1,
    version numeric(10,1),
    valid_from_date timestamp without time zone,
    valid_to_date timestamp without time zone DEFAULT '2199-12-31 23:59:59'::timestamp without time zone,
    created_by integer,
    created_date timestamp without time zone,
    modified_by integer,
    modified_date timestamp without time zone,
    fk_eqms_status_lk_id integer 
);

