ALTER TABLE organization.eqms_reg_manufacture_checklist_section_master DROP CONSTRAINT fk_ermcs_eqms_reg_manufacture_license_template_id;
ALTER TABLE organization.eqms_reg_manufacture_checklist_section_master DROP CONSTRAINT fk_ermcs_eqms_organization_id;
ALTER TABLE organization.eqms_reg_manufacture_checklist_section_master DROP CONSTRAINT ermcsm_tenant_org_ref_unique;
