ALTER TABLE organization.eqms_target_audience_type_lk DROP CONSTRAINT fk_eqms_organization_id;
ALTER TABLE organization.eqms_target_audience_type_lk DROP CONSTRAINT eqms_target_audience_type_lk_tenant_org_ref_unique;
