ALTER TABLE risk_management.eqms_project_risk_assessment_matrix DROP CONSTRAINT fk_epram_risk_assessment_matrix_template_id;
ALTER TABLE risk_management.eqms_risk_assessment_matrix_template DROP CONSTRAINT fk_eramt_risk_severity_level_template_id;
ALTER TABLE risk_management.eqms_risk_assessment_matrix_template DROP CONSTRAINT fk_eramt_risk_probability_level_template_id;
ALTER TABLE risk_management.eqms_risk_assessment_matrix_template DROP CONSTRAINT fk_eramt_organization_id;
ALTER TABLE risk_management.eqms_project_risk_assessment_matrix DROP CONSTRAINT fk_epram_project_risk_severity_level_id;
ALTER TABLE risk_management.eqms_project_risk_assessment_matrix DROP CONSTRAINT fk_epram_project_risk_probability_level_id;
ALTER TABLE risk_management.eqms_project_risk_assessment_matrix DROP CONSTRAINT fk_epram_organization_id;
ALTER TABLE risk_management.eqms_risk_assessment_matrix_template DROP CONSTRAINT eqms_risk_assessment_matrix_template_tenant_org_ref_unique;
