CREATE TABLE purchase.eqms_purchase_order_history (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fk_eqms_purchase_order_id integer,
    eqms_tenant_key integer,
    fk_eqms_organization_id integer,
    fk_eqms_purchase_order_type_lk_id integer,
    po_number character varying(100),
    po_date timestamp without time zone,
    tentative_delivery_date timestamp without time zone,
    quotation_reference character varying(100),
    fk_eqms_vendor_id integer,
    total_ex_work numeric(12,2),
    packaging_transport numeric(12,2),
    sub_total numeric(12,2),
    gst numeric(12,2),
    total_amount numeric(12,2),
    record_status smallint DEFAULT 1,
    version numeric(10,1),
    valid_from_date timestamp without time zone,
    valid_to_date timestamp without time zone DEFAULT '2199-12-31 23:59:59'::timestamp without time zone,
    created_by integer,
    created_date timestamp without time zone,
    modified_by integer,
    modified_date timestamp without time zone,
    fk_eqms_status_lk_id integer 
);

