ALTER TABLE risk_management.eqms_rmp_residual_risk_acceptability_criteria DROP CONSTRAINT fk_errrac_rmp_residual_risk_acceptability_type_lk_id;
ALTER TABLE risk_management.eqms_rmp_residual_risk_acceptability_criteria DROP CONSTRAINT fk_errrac_project_risk_severity_level_id;
ALTER TABLE risk_management.eqms_rmp_residual_risk_acceptability_criteria DROP CONSTRAINT fk_errrac_project_risk_probability_level_id;
ALTER TABLE risk_management.eqms_rmp_residual_risk_acceptability_criteria DROP CONSTRAINT fk_errrac_organization_id;
