ALTER TABLE infrastructure.eqms_infrastructure_request_supporting_files DROP CONSTRAINT fk_ei_infrastructure_request_id;
ALTER TABLE infrastructure.eqms_infrastructure_request_supporting_files DROP CONSTRAINT fk_ei_organization_id;
ALTER TABLE infrastructure.eqms_infrastructure_request_supporting_files DROP CONSTRAINT fk_ei_file_id;
ALTER TABLE infrastructure.eqms_infrastructure_request DROP CONSTRAINT fk_esf_status_lk_id;
ALTER TABLE infrastructure.eqms_infrastructure_request DROP CONSTRAINT fk_eir_infrastructure_type_lk_id;
ALTER TABLE infrastructure.eqms_infrastructure_request DROP CONSTRAINT fk_eir_infrastructure_category_lk_id;
ALTER TABLE infrastructure.eqms_infrastructure_request DROP CONSTRAINT fk_ei_organization_id;
