ALTER TABLE pre_production.eqms_pre_prod_jig_validation_results DROP CONSTRAINT fk_eppjvres_verification_result_lk_id;
ALTER TABLE pre_production.eqms_pre_prod_jig_validation_results DROP CONSTRAINT fk_eppjvres_pre_prod_jig_validation_report_id;
ALTER TABLE pre_production.eqms_pre_prod_jig_validation_results DROP CONSTRAINT fk_eppjvres_pre_prod_jig_fixture_acceptance_criteria_id;
ALTER TABLE pre_production.eqms_pre_prod_jig_validation_results DROP CONSTRAINT fk_eppjvres_organization_id;
ALTER TABLE pre_production.eqms_pre_prod_jig_validation_report_supporting_file DROP CONSTRAINT fk_eppjvrsf_pre_prod_jig_validation_report_id;
ALTER TABLE pre_production.eqms_pre_prod_jig_validation_report_supporting_file DROP CONSTRAINT fk_eppjvrsf_organization_id;
ALTER TABLE pre_production.eqms_pre_prod_jig_validation_report_supporting_file DROP CONSTRAINT fk_eppjvrsf_file_id;
