ALTER TABLE organization.eqms_rmp_applicable_stage_lk DROP CONSTRAINT fk_erpasl_organization_id;
ALTER TABLE organization.eqms_rmp_applicable_stage_lk DROP CONSTRAINT eqms_rmp_applicable_stage_lk_tenant_org_ref_unique;
