ALTER TABLE organization.eqms_reg_test_checklist_section_master DROP CONSTRAINT fk_ertcs_eqms_reg_test_license_template_id;
ALTER TABLE organization.eqms_reg_test_checklist_section_master DROP CONSTRAINT fk_ertcs_eqms_organization_id;
ALTER TABLE organization.eqms_reg_test_checklist_section_master DROP CONSTRAINT eqms_reg_test_checklist_section_master_tenant_org_ref_unique;
