CREATE TABLE dnd.eqms_feasibility_study_report_history (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fk_eqms_feasibility_study_report_id integer,
    eqms_tenant_key integer,
    fk_eqms_project_id integer,
    scope text,
    design_methodology text,
    technical_feasibility text,
    project_duration character varying(100),
    training_requirements text,
    project_risks text,
    dependencies text,
    project_impact text,
    other_requirements text,
    conclusion text,
    regulatory_implications text,
    status smallint,
    record_status smallint DEFAULT 1,
    version numeric(10,1),
    valid_from_date timestamp without time zone,
    valid_to_date timestamp without time zone DEFAULT '2199-12-31 23:59:59'::timestamp without time zone,
    created_date timestamp without time zone,
    created_by integer,
    modified_date timestamp without time zone,
    modified_by integer,
    fk_eqms_organization_id integer,
    fk_eqms_feasibility_currency_lk_id integer 
);

