CREATE TABLE dnd.eqms_feasibility_study_report (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    eqms_tenant_key integer,
    fk_eqms_project_id integer,
    scope text,
    design_methodology text,
    technical_feasibility text,
    project_duration character varying(100),
    training_requirements text,
    project_risks text,
    dependencies text,
    project_impact text,
    other_requirements text,
    regulatory_implications text,
    conclusion text,
    status smallint,
    version numeric(10,1) DEFAULT 1.0,
    created_date timestamp without time zone,
    created_by integer,
    modified_date timestamp without time zone,
    modified_by integer,
    fk_eqms_organization_id integer,
    fk_eqms_feasibility_currency_lk_id integer 
);

