ALTER TABLE organization.eqms_maintenance_service_type_lk DROP CONSTRAINT fk_em_organization_id;
ALTER TABLE organization.eqms_maintenance_service_type_lk DROP CONSTRAINT unique_emstl_tnt_org_ref_id;
