CREATE TABLE dnd.eqms_dir_declaration_history (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fk_eqms_dir_declaration_id integer,
    eqms_tenant_key integer,
    fk_eqms_organization_id integer,
    is_dir_conflict integer,
    is_dir_conflict_remarks character varying(100),
    is_dir_unambiguous integer,
    is_dir_unambiguous_remarks character varying(100),
    is_dir_verifiable integer,
    is_dir_verifiable_remarks character varying(100),
    is_dir_complete integer,
    is_dir_complete_remarks character varying(100),
    declaration_date_time timestamp without time zone,
    status smallint,
    record_status smallint DEFAULT 1,
    version numeric(10,1),
    valid_from_date timestamp without time zone,
    valid_to_date timestamp without time zone DEFAULT '2199-12-31 23:59:59'::timestamp without time zone,
    created_date timestamp without time zone,
    created_by integer,
    modified_date timestamp without time zone,
    modified_by integer,
    is_dir_retested smallint,
    fk_eqms_dir_adequacy_report_id integer 
);

