CREATE TABLE sales.eqms_delivery_dispatch_history (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fk_eqms_delivery_dispatch_id integer NOT NULL,
    eqms_tenant_key integer,
    fk_eqms_organization_id integer,
    fk_eqms_quotation_id integer,
    delivery_instruction_id character varying(100),
    invoice_location character varying(255),
    encrypted_ship_to_contact_person character varying,
    encrypted_ship_to_address character varying,
    encrypted_ship_to_location character varying,
    remarks_special_instruction character varying,
    product_configuration character varying,
    expected_shipping_date timestamp without time zone,
    record_status smallint DEFAULT 1,
    version numeric(10,1),
    valid_from_date timestamp without time zone,
    valid_to_date timestamp without time zone DEFAULT '2199-12-31 23:59:59'::timestamp without time zone,
    created_by integer,
    created_date timestamp without time zone,
    modified_by integer,
    modified_date timestamp without time zone,
    fk_eqms_status_lk_id integer 
);

