ALTER TABLE risk_management.eqms_risk_review_report_summary_supporting_files DROP CONSTRAINT fk_errrsf_risk_review_report_summary_id;
ALTER TABLE risk_management.eqms_risk_review_report_summary_supporting_files DROP CONSTRAINT fk_errrsf_organization_id;
ALTER TABLE risk_management.eqms_risk_review_report_summary_supporting_files DROP CONSTRAINT fk_errrsf_file_id;
ALTER TABLE risk_management.eqms_risk_review_report_summary DROP CONSTRAINT fk_errrs_value_acceptability_lk_id;
ALTER TABLE risk_management.eqms_risk_review_report_summary DROP CONSTRAINT fk_errrs_selection_lk_id;
ALTER TABLE risk_management.eqms_risk_review_report_summary DROP CONSTRAINT fk_errrs_project_id;
ALTER TABLE risk_management.eqms_risk_review_report_summary DROP CONSTRAINT fk_errrs_organization_id;
