CREATE TABLE dnd.eqms_bom_assembly_part_details_history (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fk_eqms_bom_assembly_part_details_id integer,
    eqms_tenant_key integer,
    fk_eqms_organization_id integer,
    fk_eqms_bom_assembly_parts_id integer,
    fk_eqms_alternative_part_number_id integer,
    fk_eqms_part_purchase_type_lk_id integer,
    fk_eqms_part_type_lk_id integer,
    manufacturer_name character varying(255),
    mfg_part_number character varying(100),
    fk_eqms_part_component_type_lk_id integer,
    fk_eqms_part_quantity_type_lk_id integer,
    fk_eqms_assembly_type_lk_id integer,
    status smallint,
    record_status smallint DEFAULT 1,
    version numeric(10,1),
    valid_from_date timestamp without time zone,
    valid_to_date timestamp without time zone DEFAULT '2199-12-31 23:59:59'::timestamp without time zone,
    created_date timestamp without time zone,
    created_by integer,
    modified_date timestamp without time zone,
    modified_by integer 
);

